[package]
name = "bcs-parser"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/bcbc"

[lib]
path = "lib.rs"

[dependencies]
nom = "7"
bcbc = { path = "../bcbc" }
